replicaCount: 1

image:
  repository: 111285186890.dkr.ecr.us-east-1.amazonaws.com/eth-explorer
  pullPolicy: Always
  tag: latest

cfTokenSecret:
  name: cf-tunnel-eth-explorer
  key: token

infuraAPIKey:
  name: eth-explorer-infura
  key: api-key

service: 
  type: ClusterIP
  port: 5000

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress: {}
