apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  annotations:
    kubernetes.io/change-cause: "First deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo
        version: "1.4"
        type: db
    spec:
      containers:
      - image: mongo:3.7
        imagePullPolicy: IfNotPresent
        name: mongo
        resources: {}
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
