apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: pastebin
    labels:
        app: pastebin
spec:
    replicas: 2
    selector:
        matchLabels:
            app: pastebin
    template:
        metadata:
            labels:
                app: pastebin
        spec:
            containers:
            - name: pastebin
              image: boris/nginx-pastebin:latest
              ports:
                  - containerPort: 80
