apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:111285186890:certificate/9a70e729-49d4-4152-880a-74a13aa45d4b
  name: pwgen
  labels:
    app: pwgen
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
  selector:
    run: pwgen
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pwgen
  name: pwgen
  annotations:
    kubernetes.io/change-cause: "Reduce number of replicas"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwgen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pwgen
        version: "1.4"
        type: web
    spec:
      containers:
      - image: boris/pwgen-web:1.4
        imagePullPolicy: IfNotPresent
        name: pwgen
        resources: {}
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
