apiVersion: v1
kind: Pod
metadata:
  name: pwgen-web
spec:
  containers:
    - image: boris/pwgen-web:latest
      name: pwgen-web
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "64m"
          memory: "128Mi"
        limits:
          cpu: "128m"
          memory: "256Mi"
