apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pwgen
  name: pwgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwgen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pwgen
    spec:
      containers:
      - image: boris/pwgen:1.4
        imagePullPolicy: IfNotPresent
        name: pwgen
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
