apiVersion: v1
kind: Pod
metadata:
  name: secret-service
spec:
  containers:
    - name: nginx-secret
      image: nginx
      imagePullPolicy: Always
      volumeMounts:
      - name: secrets
        mountPath: "/tmp"
        readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: db-example-secret
