apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-tunnel-test
spec:
  selector:
    matchLabels:
      app: cf-tunnel
  template:
    metadata:
      labels:
        app: cf-tunnel
    spec:
      containers:
        - name: cf-tunnel
          image: cloudflare/cloudflared
          args:
            - tunnel
            - run
            - "--token"
            - $CF_TOKEN
          env:
            - name: CF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cf-tunnel-token
                  key: token

