apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-tunnel-test
spec:
  selector:
    matchLabels:
      app: cf-tunnel
  template:
    metadata:
      labels:
        app: cf-tunnel
    spec:
      containers:
        - name: cf-tunnel
          image: cloudflare/cloudflared
          env:
            - name: CF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cf-tunnel-token
                  key: token
          args:
            - tunnel
            - run
            - "--token"
            - TBD
        - name: nginx
          image: nginx:1.25.3
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          env:
            - name: CF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cf-tunnel-token
                  key: token
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
