apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-tunnel-nginx-test
spec:
  selector:
    matchLabels:
      app: cf-tunnel-nginx
  template:
    metadata:
      labels:
        app: cf-tunnel-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.3
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
