apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: networking
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Santiago"
        - name: WEBPASSWORD
          value: "secret"
        volumeMounts:
        - name: pihole-storage
          mountPath: "/etc"
      volumes:
      - name: pihole-storage
        persistentVolumeClaim:
          claimName: pihole-storage
