apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pwgen
  namespace: public-api
spec:
  selector:
    matchLabels:
      app: pwgen
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pwgen
        version: "1.7"
        type: web
    spec:
      containers:
      - image: boris/pwgen-web:1.7
        imagePullPolicy: IfNotPresent
        name: pwgen
        resources: {}
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

