apiVersion: v1
kind: Service
metadata:
  name: pwgen
  namespace: public-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 5000
  selector:
    app: pwgen
