#How to use this example.
#Run `kubectl create secret generic db-example-secret secrets/db-example.json`
#Deploy the pod with `kubectl create -f service-with-secret.yaml`
#The secret file will be available on /tmp
#Keep in mind that is highly UNRECOMMENDED control-versioning secrets file
apiVersion: v1
kind: Pod
metadata:
  name: secret-service
spec:
  containers:
    - name: nginx-secret
      image: nginx
      imagePullPolicy: Always
      volumeMounts:
      - name: secrets
        mountPath: "/tmp"
        readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: db-example-secret
