apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: znc
  name: znc
  annotations:
    kubernetes.io/change-cause: "Upgrade to 1.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: znc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: znc
        version: "1.1.7"
        type: irc
    spec:
      containers:
      - image: boris/znc:latest
        imagePullPolicy: IfNotPresent
        name: irc-bouncer
        resources: {}
        ports:
        - containerPort: 31337
      dnsPolicy: ClusterFirst
      restartPolicy: Always
