replicaCount: 1

image:
  repository: 111285186890.dkr.ecr.us-east-1.amazonaws.com/fastapi-btc-calc
  pullPolicy: IfNotPresent
  tag: 49480cf

cfTokenSecret:
  name: cf-tunnel-token-fastapi-btc
  key: token

service:
  type: ClusterIP
  port: 8000

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress: {}
