apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-btc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-btc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fastapi-btc
        version: "1.0"
        type: api
    spec:
      containers:
        - name: cf-tunnel
          image: cloudflare/cloudflared
          env:
            - name: CF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cf-tunnel-token-fastapi-btc
                  key: token
          args:
            - tunnel
            - run
            - --token
            - $(CF_TOKEN)
        - name: fastapi-btc
          image: 111285186890.dkr.ecr.us-east-1.amazonaws.com/fastapi-btc-calc:0907b10
          ports:
          - containerPort: 9000
