apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot
        image: 111285186890.dkr.ecr.us-east-1.amazonaws.com/telegram-bot:b929eb2
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-token-fastapi-btc
              key: token
        - name: CMC_TOKEN
          valueFrom:
            secretKeyRef:
              name: cmc-token-fastapi-btc
              key: token
