apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-stats
  namespace: networking
spec:
  selector:
    matchLabels:
      app: bitcoin-stats
  replicas: 1
  template:
    metadata:
      labels:
        app: bitcoin-stats
    spec:
      containers:
        - name: bitcoin-stats
          image: boris/bitcoin-prometheus:0.1
          ports:
            - containerPort: 5001
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-stats
  namespace: networking
spec:
  selector:
    app: bitcoin-stats
  type: LoadBalancer
  ports:
    - port: 5001
      name: tcp5001
      targetPort: 5001
      nodePort: 30051
